<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement("DROP VIEW IF EXISTS `enhanced_orders_view`;");
        DB::statement("CREATE VIEW `enhanced_orders_view` AS select `o`.`order_id` AS `order_id`,`o`.`order_number` AS `order_number`,`o`.`user_id` AS `user_id`,`u`.`full_name` AS `user_name`,`o`.`orders_address` AS `orders_address`,`o`.`vendor_id` AS `vendor_id`,`v`.`vendor_name` AS `vendor_name`,`o`.`vehicle_id` AS `vehicle_id`,`vm`.`name` AS `make_name`,`vmod`.`name` AS `model_name`,`veh`.`year` AS `year`,`veh`.`license_plate_number` AS `license_plate_number`,group_concat(`od`.`sub_service_id` separator ',') AS `sub_service_ids`,group_concat(`ss`.`name` separator ',') AS `sub_service_names`,sum(`od`.`total_price`) AS `services_total_price`,group_concat(distinct `s`.`service_id` separator ',') AS `service_ids`,group_concat(distinct `s`.`service_name` separator ',') AS `service_names`,`fau`.`name` AS `fault_type_name`,`o`.`order_status` AS `order_status`,`o`.`order_type` AS `order_type`,`o`.`orders_coupon_id` AS `orders_coupon_id`,`o`.`orders_paymentmethod` AS `orders_paymentmethod`,`o`.`orders_pricedelivery` AS `orders_pricedelivery`,`o`.`order_date` AS `order_date`,`o`.`total_amount` AS `total_amount`,`o`.`workshop_amount` AS `workshop_amount`,`o`.`app_commission` AS `app_commission`,`o`.`payment_status` AS `payment_status`,`o`.`notes` AS `notes`,`a`.`address_name` AS `address_name`,`a`.`address_street` AS `address_street`,`a`.`address_city` AS `address_city`,`a`.`address_latitude` AS `address_latitude`,`a`.`address_longitude` AS `address_longitude` from ((((((((((`orders` `o` left join `users` `u` on(`o`.`user_id` = `u`.`user_id`)) left join `vendors` `v` on(`o`.`vendor_id` = `v`.`vendor_id`)) left join `vehicles` `veh` on(`o`.`vehicle_id` = `veh`.`vehicle_id`)) left join `car_makes` `vm` on(`veh`.`car_make_id` = `vm`.`make_id`)) left join `car_models` `vmod` on(`veh`.`car_model_id` = `vmod`.`model_id`)) left join `addresses` `a` on(`o`.`orders_address` = `a`.`address_id`)) left join `order_details` `od` on(`o`.`order_id` = `od`.`order_id`)) left join `sub_services` `ss` on(`od`.`sub_service_id` = `ss`.`sub_service_id`)) left join `services` `s` on(`ss`.`service_id` = `s`.`service_id`)) left join `fault_types` `fau` on(`o`.`fault_type_id` = `fau`.`fault_id`)) group by `o`.`order_id`;");
        DB::statement("DROP VIEW IF EXISTS `ordersview`;");
        DB::statement("CREATE VIEW `ordersview` AS select `o`.`order_id` AS `order_id`,`o`.`order_number` AS `order_number`,`o`.`user_id` AS `user_id`,`o`.`orders_address` AS `orders_address_fk`,`o`.`vendor_id` AS `vendor_id`,`o`.`vehicle_id` AS `vehicle_id`,`o`.`fault_type_id` AS `fault_type_id`,`o`.`order_status` AS `order_status`,`o`.`order_type` AS `order_type`,`o`.`orders_coupon_id` AS `orders_coupon_id`,`o`.`orders_paymentmethod` AS `orders_paymentmethod`,`o`.`orders_pricedelivery` AS `orders_pricedelivery`,`o`.`order_date` AS `order_date`,`o`.`total_amount` AS `total_amount`,`o`.`workshop_amount` AS `workshop_amount`,`o`.`app_commission` AS `app_commission`,`o`.`payment_status` AS `payment_status`,`o`.`notes` AS `notes`,`o`.`is_scheduled` AS `is_scheduled`,max(`os`.`scheduled_datetime`) AS `scheduled_datetime`,`a`.`address_id` AS `address_id`,`a`.`address_user_id` AS `address_user_id`,`a`.`address_name` AS `address_name`,`a`.`address_street` AS `address_street`,`a`.`address_city` AS `address_city`,`a`.`address_latitude` AS `address_latitude`,`a`.`address_longitude` AS `address_longitude`,`a`.`address_status` AS `address_status` from ((`orders` `o` left join `addresses` `a` on(`o`.`orders_address` = `a`.`address_id`)) left join `order_scheduling` `os` on(`o`.`order_id` = `os`.`order_id`)) group by `o`.`order_id`;");
        DB::statement("DROP VIEW IF EXISTS `order_calculations_view`;");
        DB::statement("CREATE VIEW `order_calculations_view` AS select `od`.`order_id` AS `order_id`,sum(`od`.`quantity` * `od`.`unit_price`) AS `subtotal`,sum(`od`.`discount`) AS `total_discounts`,sum(`od`.`total_price`) AS `total_services_amount`,`o`.`orders_pricedelivery` AS `delivery_price`,`o`.`total_amount` AS `total_amount`,`o`.`workshop_amount` AS `workshop_amount`,`o`.`app_commission` AS `app_commission` from (`order_details` `od` join `orders` `o` on(`od`.`order_id` = `o`.`order_id`)) group by `od`.`order_id`;");
        DB::statement("DROP VIEW IF EXISTS `order_details_view`;");
        DB::statement("CREATE VIEW `order_details_view` AS select `od`.`detail_id` AS `detail_id`,`od`.`order_id` AS `order_id`,`o`.`is_scheduled` AS `order_is_scheduled`,`os_main`.`scheduled_datetime` AS `order_scheduled_datetime`,`od`.`sub_service_id` AS `sub_service_id`,`ss`.`service_id` AS `service_id`,json_unquote(json_extract(`ss`.`name`,'$')) AS `sub_service_name`,json_unquote(json_extract(`s`.`service_name`,'$')) AS `service_name`,`od`.`quantity` AS `quantity`,`od`.`unit_price` AS `unit_price`,`od`.`discount` AS `discount`,`od`.`total_price` AS `total_price`,`od`.`created_at` AS `created_at`,`od`.`updated_at` AS `updated_at` from (((`order_details` `od` join `sub_services` `ss` on(`od`.`sub_service_id` = `ss`.`sub_service_id`)) join `services` `s` on(`ss`.`service_id` = `s`.`service_id`)) left join `orders` `o` on(`od`.`order_id` = `o`.`order_id`)) left join (select `order_scheduling`.`order_id` AS `order_id`,max(`order_scheduling`.`scheduled_datetime`) AS `scheduled_datetime` from `order_scheduling` group by `order_scheduling`.`order_id`) `os_main` on(`o`.`order_id` = `os_main`.`order_id`);");
        DB::statement("DROP VIEW IF EXISTS `order_summary_view`;");
        DB::statement("CREATE VIEW `order_summary_view` AS select `o`.`order_id` AS `order_id`,`o`.`order_number` AS `order_number`,`o`.`user_id` AS `user_id`,`u`.`full_name` AS `user_name`,`o`.`vendor_id` AS `vendor_id`,json_unquote(json_extract(`v`.`vendor_name`,'$')) AS `vendor_name`,`o`.`vehicle_id` AS `vehicle_id`,json_unquote(json_extract(`vm`.`name`,'$')) AS `make_name`,json_unquote(json_extract(`vmod`.`name`,'$')) AS `model_name`,`o`.`order_status` AS `order_status`,`o`.`payment_status` AS `payment_status`,`o`.`order_date` AS `order_date`,`o`.`total_amount` AS `total_amount`,count(`od`.`detail_id`) AS `service_count`,sum(`od`.`total_price`) AS `services_total` from (((((`orders` `o` left join `users` `u` on(`o`.`user_id` = `u`.`user_id`)) left join `vendors` `v` on(`o`.`vendor_id` = `v`.`vendor_id`)) left join `vehicles` `veh` on(`o`.`vehicle_id` = `veh`.`vehicle_id`)) left join `car_makes` `vm` on(`veh`.`car_make_id` = `vm`.`make_id`)) left join `car_models` `vmod` on(`veh`.`car_model_id` = `vmod`.`model_id`)) left join `order_details` `od` on(`o`.`order_id` = `od`.`order_id`)) group by `o`.`order_id`;");
        DB::statement("DROP VIEW IF EXISTS `vehicle_essential_info`;");
        DB::statement("CREATE VIEW `vehicle_essential_info` AS select `v`.`vehicle_id` AS `vehicle_id`,`u`.`user_id` AS `user_id`,`cm`.`make_id` AS `make_id`,`cmod`.`model_id` AS `model_id`,`cm`.`name` AS `make_name`,`cm`.`logo` AS `make_logo`,`cmod`.`name` AS `model_name`,`v`.`year` AS `year`,`v`.`license_plate_number` AS `license_plate_number`,`v`.`status` AS `status` from (((`vehicles` `v` left join `users` `u` on(`v`.`user_id` = `u`.`user_id`)) left join `car_makes` `cm` on(`v`.`car_make_id` = `cm`.`make_id`)) left join `car_models` `cmod` on(`v`.`car_model_id` = `cmod`.`model_id`));");
    }

    public function down(): void
    {
        DB::statement("DROP VIEW IF EXISTS `enhanced_orders_view`;");
        DB::statement("DROP VIEW IF EXISTS `ordersview`;");
        DB::statement("DROP VIEW IF EXISTS `order_calculations_view`;");
        DB::statement("DROP VIEW IF EXISTS `order_details_view`;");
        DB::statement("DROP VIEW IF EXISTS `order_summary_view`;");
        DB::statement("DROP VIEW IF EXISTS `vehicle_essential_info`;");
    }
};
